<?php

/**
 * @file
 * Main code for CKEditor CodeMirror module.
 */

/**
 * Implements hook_library_info().
 */
function ckeditor_codemirror_library_info() {
  $path_prefix = backdrop_get_path('module', 'ckeditor_codemirror') . '/library/codemirror/';
  $library['ckeditor.codemirror'] = array(
    'title' => 'CKEditor CodeMirror plugin',
    'website' => 'https://w8tcha.github.io/CKEditor-CodeMirror-Plugin',
    'version' => '1.18.7',
    'js' => array(
      $path_prefix . 'plugin.js',
      $path_prefix . 'js/codemirror.min.js',
    ),
    'css' => array(
      $path_prefix . 'css/codemirror.min.css',
    ),
  );

  return $library;
}

/**
 * Implements hook_ckeditor_plugins().
 */
function ckeditor_codemirror_ckeditor_plugins() {
  $library_path = backdrop_get_path('module', 'ckeditor_codemirror') . '/library/codemirror';
  return array(
    'codemirror' => array(
      'path' => $library_path,
      'file' => 'plugin.js',
      'enabled callback' => TRUE,
    ),
  );
}
